### ISSUE TITLE
SSP Synthesis (2022 USYD)

### ISSUE THREAD

**Issue by kym834** [OpenSourceMycetoma/Series-2-Aminothiazoles#10]
This year the SSP student were working on creating 10 compounds. (see below) These compounds build upon the work from last year where it was determined that the 2-pyridyl (green) is important for activity (see #6). These compounds were synthesised using the [general synthesis route](https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/wiki/General-Synthesis-Route). At the time of posting the compounds are being characterised and the students will be analysing the NMR, MS, IR and HPLC in the next week to determine if they have made the expected compounds.
![image](https://user-images.githubusercontent.com/61669512/195509061-0dfcea3f-9bf8-403e-9cf9-e83b3f58dd1f.png)

**Comment by mattodd** [comment]
OK, great @kym834, thanks! So these are the "SSP" compounds made by the Uni of Sydney. If you've links to the data the students collect, that will be useful for others in the future, too. 

Also thanks for the other set of compounds you mentioned [here](https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/issues/9#issuecomment-1277001444) made by a schools workshop, and for updating the wiki. 

So, in terms of planning @kym834 , do you have a set of compounds you are targeting in the coming year? Some of the school students in the UK are keen to try this chemistry and we don't want to overlap. Are they essentially free to try anything at this point?
@PaulMcKeatingSevenoaks

**Comment by wwjvdsande** [comment]
@kym834 the in vitro data are added to the [spreadsheet](http://tinyurl.com/MycetomaMols)

**Comment by kym834** [comment]
Summary of the in vitro activities below:

Couple of points:

* 2-pyridyl is again shown to be important for activity
* when have 2-pyridyl can make modification to other ring system that is tolerated though nothing better found yet.
* Chloro derivatives open the SAR to some coupling reactions to build on the core structure

<img width ="800" src="https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/assets/61669512/4655462e-4c43-4035-b049-0d763aa8268a">

<img width ="800" src="https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/assets/61669512/5e4020d8-9e1a-468b-ac5a-6d67b8842aa0">

All synthesis and biological evaluation data added to wiki. Closing issue.
