### ISSUE TITLE
MYOS numbers for Series 2

### ISSUE THREAD

**Issue by kym834** [OpenSourceMycetoma/Series-2-Aminothiazoles#5]
Hi All, 

We have a number of series 2 samples synthesised and ready to be shipped and they are in need MYOS numbers. 

At the moment the master list has a sheet for "MYOS (fenarimol analogues)". To keep track of the numbering I'm suggesting making a master sheet for all MYOS compounds and adding in a 'series' column. Would @OpenSourceMycetoma/corecontrib  be happy with this or does someone have a suggestion which they think will work better?

@mattodd @fantasy121 @dmitrij176 @Wilson-Lm @wwjvdsande @bendndi

**Comment by mattodd** [comment]
Yes, same Myos coding system, same sheet, add Series column for simplicity.
Note that if you add a column for "URL" or something like that we can use
the new PlanetaryForge Twitter bot to advertise the molecules.

**Comment by wwjvdsande** [comment]
Yes, adding a series column for us biologists is very helpful ;-).

**Comment by kym834** [comment]
Thanks All! A series column has been added to the Master List and the new series 2 compounds added. 

I'm more than happy to put in a 'URL' column. I actually have one in my own excel spreadsheets so that I don't have to search my whole ELN on GitHub to find the notebook entry. I think it would be great to have a direct link to the ELN/source in the master sheet for each compound we make. Maybe something to discuss in [this months meeting](https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/issues/58)

Closing issue as this has now been resolved.
