### ISSUE TITLE
High school synthesis workshop 2022

### ISSUE THREAD

**Issue by kym834** [OpenSourceMycetoma/Series-2-Aminothiazoles#9]
We are running a workshop with high school students in late May/early June who will work on the synthesis of a few more compounds for this series. They will be looking at changing up the aniline used in the synthesis to explore different aromatic groups attached to the amine of the 2-aminothiazoles (R in the image below).

![image](https://user-images.githubusercontent.com/61669512/162643498-cac8f813-1c90-4de6-99a9-6b2bfd4350cc.png)

@wwjvdsande -  as these compounds are not well known, we are wondering if you have resources or capacity to run a tox screen of the hit? Or maybe know of someone who could do it on our behalf? We'd love to check that these compounds aren't crazy toxic before we set off trying to make them with students.

@OpenSourceMycetoma/corecontrib - If anyone has any other ideas about how we could investigate the safety, love to hear it too!

**Comment by wwjvdsande** [comment]
@kym834 for us we typically only test if the compounds are toxic to the larvae. Since the larvae can stand higher concentrations of certain toxic compounds than humans can I don't think this is a good solution for you.

**Comment by kym834** [comment]
Here are the compounds we are intending to make in this round of synthesis. @mattodd @AndyBishopSevenoaks
![BGxDDI Reaction Scheme](https://user-images.githubusercontent.com/61669512/166193942-f3430768-91db-486b-a302-9bf42ad14c4c.png)

**Comment by kym834** [comment]
@wwjvdsande and @MA-Jjingyi we've prepared 6 of these compounds we made with students for shipment with FedEx. They'll be picked up on Monday (AU time) and are estimated to arrive Thursday (Ntherlands time). 

Also, I'm presenting at a conference on the 6th of July. Do you think we'd have the in vitro results by then? Love to present this 🙂

**Comment by MA-Jjingyi** [comment]
> @wwjvdsande and @MA-Jjingyi we've prepared 6 of these compounds we made with students for shipment with FedEx. They'll be picked up on Monday (AU time) and are estimated to arrive Thursday (Ntherlands time).
> 
> Also, I'm presenting at a conference on the 6th of July. Do you think we'd have the in vitro results by then? Love to present this 🙂

@kym834 Hi, kymberley. thanks for your delivery. when we get the package, we will let you know.  but it is a pity we cann't finish the in vitro test before your presentation.

**Comment by mattodd** [comment]
This is really great. @kym834 are the compounds in the Master List with the relevant MyOS codes, and could they please make an appearance [here](https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/wiki/All-Compounds-Evaluated-To-Date)?

**Comment by wwjvdsande** [comment]
@kym834 we have added the six compounds to our screening plate, three extra compounds arrived. Where they also from this group?

**Comment by kym834** [comment]
The workshops we ran in May/June of 2022 resulted in 6 new compounds to be added to the series 2 library. The compounds that were synthesised, characterised and shipped to Wendy and Co. are shown below.
<img width="1012" alt="Screen Shot 2022-10-13 at 3 04 57 pm" src="https://user-images.githubusercontent.com/61669512/195497045-d44f3900-e756-4061-87f4-f8a509c7f58e.png">

The other 4 compounds that we had planned to make were not synthesised as there were issues with generating the thiourea starting materials.

**Comment by wwjvdsande** [comment]
@kym834 the compounds are tested and the results are added to [spreadsheet](http://tinyurl.com/MycetomaMols) MYOS_00315 and MYOS_00317 seemed most active out of this set.

**Comment by kym834** [comment]
Summary of the in vitro activities below:

Couple of points:
* Modification at 4 position seems to be tolerated and give similar activity to hit compound.
* 3 position less tolerant of modification.
<img width ="800" src="https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/assets/61669512/a9166802-fcfa-4c99-9d92-e49d1347ae8a">
